---
title: "Crystallography"
author: "Joanna So³omiewicz"
date: "15 listopada 2018"
output: 
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
---

#Loading libraries
```{r loading libraries, message = FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyr)
library(knitr)
library(corrplot)
library(caret)
library(data.table)
```

#Reading data
```{r reading data, cache = TRUE}
removable_columns <- c("title", "pdb_code", "res_id", "chain_id", "local_res_atom_count", "local_res_atom_non_h_occupancy_sum", "local_res_atom_non_h_electron_occupancy_sum", "local_res_atom_C_count", "local_res_atom_N_count", "local_res_atom_O_count", "local_res_atom_S_count", "dict_atom_C_count", "dict_atom_N_count", "dict_atom_O_count", "dict_atom_S_count", "skeleton_data", "skeleton_cycle_4", "skeleton_diameter", "skeleton_cycle_6", "skeleton_cycle_7", "skeleton_closeness_006_008", "skeleton_closeness_002_004", "skeleton_cycle_3", "skeleton_avg_degree", "skeleton_closeness_004_006", "skeleton_closeness_010_012", "skeleton_closeness_012_014", "skeleton_edges", "skeleton_radius", "skeleton_cycle_8_plus", "skeleton_closeness_020_030", "skeleton_deg_5_plus", "skeleton_closeness_016_018", "skeleton_closeness_008_010", "skeleton_closeness_018_020", "skeleton_average_clustering", "skeleton_closeness_040_050", "skeleton_closeness_014_016", "skeleton_center", "skeleton_closeness_000_002", "skeleton_density", "skeleton_closeness_030_040", "skeleton_deg_4", "skeleton_deg_0", "skeleton_deg_1", "skeleton_deg_2", "skeleton_deg_3", "skeleton_graph_clique_number", "skeleton_nodes", "skeleton_cycles", "skeleton_cycle_5", "skeleton_closeness_050_plus", "skeleton_periphery", "fo_col", "fc_col", "weight_col", "grid_space", "solvent_radius", "solvent_opening_radius", "part_step_FoFc_std_min", "part_step_FoFc_std_max", "part_step_FoFc_std_step")

data <- fread("./all_summary.csv", nrows = 10000, header = TRUE, drop = removable_columns)
dim(data)
```

#Processing missing data
```{r processing missing data, cache = TRUE}
dim(data)
data <- data %>% 
  drop_na()
dim(data)
```

#Deleting chosen ligands
```{r deleting chosen ligands}
deletable_res_name <- c("UNK", "UNX", "UNL", "DUM", "N", "BLOB", "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE", "LEU", "LYS", "MET", "MSE", "PHE", "PRO", "SEC", "SER", "THR", "TRP", "TYR", "VAL", "DA", "DG", "DT", "DC", "DU", "A", "G", "T", "C", "U", "HOH", "H20", "WAT")
data <- data %>% filter(!res_name %in% deletable_res_name)
dim(data)
```

#Data summary
```{r data summary}
statistics <- data %>%
  select(res_name, blob_volume_coverage, blob_volume_coverage_second)
kable(summary(statistics))
dim(data)
```

#50 most popular ligands
```{r 50 most popular ligands}
popular_ligands <- data %>% 
  select(res_name) %>%
  count(res_name, sort = TRUE) %>%
  slice(1:50)

popular_names_vector <- popular_ligands %>%
  pull(res_name)

data <- data %>% filter(res_name %in% popular_names_vector)
dim(data)
```

#Cardinality of ligands by name
```{r cardinality of ligands}
plot_ligands <- ggplot(popular_ligands, aes(x = reorder(res_name, -n), y = n, fill = n)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("ligand")+
  labs(title = "Cardinality of ligands by name")

ggplotly(plot_ligands)
```

#Correlation between variables
```{r correlation between variables}
data %>%
  select_if(is.numeric) %>%
  cor %>%
  corrplot(method = "circle", tl.col = "black", tl.srt = 45)
```

#Distribution of atom and electron count
```{r distribution of atom and electron count}
plot_atom <- ggplot(data, aes(x = local_res_atom_non_h_count)) + 
  geom_density(alpha = .3, fill = "#00CECB", color = NA) +
  xlab("atom count") +
  labs(title = "Atom count distribution")

ggplotly(plot_atom)

plot_electron <- ggplot(data, aes(x = local_res_atom_non_h_electron_sum)) + 
  geom_density(alpha = .3, fill = "#FF5E5B", color = NA) +
  xlab("electron count") +
  labs(title = "Electron count distribution")

ggplotly(plot_electron)
```

#Distribution of part_01 columns
```{r distribution of part_01 columns}
plot_part_data <- data %>%
  select(contains("part_01")) %>%
  gather(part, value, 1:106)

dim(plot_part_data)

plot_part_data_1 <- plot_part_data[1:118926,]
plot_part_data_2 <- plot_part_data[118927:237852,]
plot_part_data_3 <- plot_part_data[237853:356778,]
plot_part_data_4 <- plot_part_data[356779:475704,]
plot_part_data_5 <- plot_part_data[475705:594630,]
plot_part_data_6 <- plot_part_data[594631:700342,]

plot_ly(plot_part_data_1, x = plot_part_data_1$part, y = plot_part_data_1$value, type = 'box')
plot_ly(plot_part_data_2, x = plot_part_data_2$part, y = plot_part_data_2$value, type = 'box')
plot_ly(plot_part_data_3, x = plot_part_data_3$part, y = plot_part_data_3$value, type = 'box')
plot_ly(plot_part_data_4, x = plot_part_data_4$part, y = plot_part_data_4$value, type = 'box')
plot_ly(plot_part_data_5, x = plot_part_data_5$part, y = plot_part_data_5$value, type = 'box')
plot_ly(plot_part_data_6, x = plot_part_data_6$part, y = plot_part_data_6$value, type = 'box')
```

#Greatest inconsistency in classes
##Atom
```{r greatest inconsistency in atom}
data %>%
  select(res_name, local_res_atom_non_h_count, dict_atom_non_h_count) %>%
  group_by(res_name) %>%
  summarise(atom_inconsistency = mean(abs(local_res_atom_non_h_count - dict_atom_non_h_count))) %>%
  arrange(-atom_inconsistency) %>%
  slice(1:10) %>%
  kable()
```

##Electron
```{r greatest inconsistency in electron}
data %>%
  select(res_name, local_res_atom_non_h_electron_sum, dict_atom_non_h_electron_sum) %>%
  group_by(res_name) %>%
  summarise(electron_inconsistency = mean(abs(local_res_atom_non_h_electron_sum - dict_atom_non_h_electron_sum))) %>%
  arrange(-electron_inconsistency) %>%
  slice(1:10) %>%
  kable()
```

#Linear regression
##Atom count
```{r linear regression atom}
data_partition <- data %>%
  select_if(is.numeric)

set.seed(111)
partition <- createDataPartition(y = data_partition$local_res_atom_non_h_count, p = 0.7, list = FALSE)
data_train <- data %>%
  slice(partition)
data_test <- data %>%
  slice(-partition)
dim(data_train)
dim(data_test)

set.seed(111)
fit <- train(local_res_atom_non_h_count ~ ., data = data_train, method = "lm")
set.seed(111)
prediction <- predict(fit, newdata = data_test)
fit
postResample(pred = prediction, obs = data_test$local_res_atom_non_h_count)
```

##Electron count
```{r linear regression electron}
data_partition <- data %>%
  select_if(is.numeric)

set.seed(111)
partition <- createDataPartition(y = data_partition$local_res_atom_non_h_electron_sum, p = 0.7, list = FALSE)
data_train <- data %>%
  slice(partition)
data_test <- data %>%
  slice(-partition)
dim(data_train)
dim(data_test)

set.seed(111)
fit <- train(local_res_atom_non_h_electron_sum ~ ., data = data_train, method = "lm")
set.seed(111)
prediction <- predict(fit, newdata = data_test)
fit
postResample(pred = prediction, obs = data_test$local_res_atom_non_h_electron_sum)
```

